pipeline:
  dummy:
    image: quay.io/ukhomeofficedigital/cdp-ci:0.4.1
    commands:
      - echo dummy
    when:
      branch: [CDMP-2264-dummy]

  trigger_deploy:
      secrets:
        - drone_server
        - drone_token
        - default_environment
      image: quay.io/ukhomeofficedigital/drone-trigger:latest
      drone_server: ${DRONE_SERVER}
      repo: UKHomeOffice/cdp-environments-test
      branch: [master, CDMP-2264]
      deploy_to: ${DEFAULT_ENVIRONMENT:-cdp-dev}
      # params: "IMAGE_NAME=foo/bar:${DRONE_COMMIT_SHA},APP_ID=123"