pipeline:
  trigger_deploy:

      secrets:
        - drone_server
      image: quay.io/ukhomeofficedigital/drone-trigger:latest
      drone_server: ${DRONE_SERVER}
      repo: github.com/UKHomeOffice/cdp-environments-test
      branch: [master, CDMP-2264]
      deploy_to: cdp-dev
      # params: "IMAGE_NAME=foo/bar:${DRONE_COMMIT_SHA},APP_ID=123"