---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${PERF_TEST_NAME}
spec:
  # LPPM - 16May2019 - WARNING: this should be set to zero; 
  # otherwise, the job will keep on being re-tried and 
  # cause issues with the test script if SLAs are breached.
  backoffLimit: 0
  activeDeadlineSeconds: ${PERF_TEST_TIMEOUT}
  ttlSecondsAfterFinished: 30

  template:
    spec:
      securityContext:
        fsGroup: 1000

      containers:
      - name: taurus-perf-test
        image: quay.io/ukhomeofficedigital/docker-taurus:latest
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: bzt-report-write-access-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: bzt-report-write-access-creds
                key: aws_secret_access_key
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: access-token
                key: access_token
          - name: PERF_TESTS_BUCKET
            valueFrom:
              secretKeyRef:
                name: perf-tests-bucket
                key: perf_tests_bucket
        command: 
          # run-bzt.sh is mounted from a config map
          # to allow us to run bzt from the image but also copy the output to S3
          - sh
          - -c
          - "sh /bzt-scripts/run-bzt.sh ${PERF_TEST_CONF_GLOB}"

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000

        volumeMounts:
          - name: bzt-tests-scripts
            mountPath: /bzt-scripts
          - name: bzt-tests-config
            mountPath: /bzt-config

      restartPolicy: Never

      volumes:
      - name: bzt-tests-scripts
        configMap:
          name: bzt-tests-scripts
      - name: bzt-tests-config
        configMap:
          name: bzt-tests-config


