---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${PERF_TEST_NAME}
spec:
  # LPPM - 16May2019 - WARNING: this should be set to zero; 
  # otherwise, the job will keep on being re-tried and 
  # cause issues with the test script if SLAs are breached.
  backoffLimit: 0
  activeDeadlineSeconds: ${PERF_TEST_TIMEOUT}
  ttlSecondsAfterFinished: 30

  template:
    spec:
      securityContext:
        fsGroup: 1000

      containers:
      - name: taurus-perf-test
        image: quay.io/ukhomeofficedigital/docker-taurus:latest
        imagePullPolicy: Always
        env:
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: access-token
                key: access_token
        command: 
          - sh
          - -c
          - "bzt -l bzt.log /bzt-config/${PERF_TEST_CONF_GLOB}"

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000

        volumeMounts:
          # - name: bzt
          #   mountPath: /bzt

          - name: bzt-tests-config
            mountPath: /bzt-config

      restartPolicy: Never

      volumes:
      # - name: bzt
      #   hostPath:
      #     path: /bzt 
      #     type: Directory

      - name: bzt-tests-config
        configMap:
          name: bzt-tests-config


